cuchanoble/urls.py
from django.urls import path, include
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from perros import views as perrosviews


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',  include('perros.urls', namespace='perros')),
    path('accounts/', include('allauth.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

"""
app_name = 'cuchanoble'
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include("perros.urls", namespace="perros")),
	url(r'^accounts/', include('allauth.urls'),),
]
"""

perros/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from rest_framework.urlpatterns import format_suffix_patterns
from django.conf.urls.static import static
from django.conf import settings
from .views import (
  perros_display,
  perros_subir,
  perros_actualizar,
  perros_detalles,
  perros_inicio,
  perros_borrar,
  perros_moderacion,
  perros_moderacion_editar,
  perros_borrar_moderacion,
  perros_api_listar,
  perros_api_crear,
  perros_api
  )

app_name = 'perros'
urlpatterns = [

   	#CRUD
    url(r'^$', perros_inicio, name='index'),
    url(r'^perros/lista/$', perros_display, name='lista'),
    url(r'^perros/detalles/(?P<id>\d+)/$', perros_detalles, name='detalles'),
    url(r'^perros/subir/$', perros_subir, name='subir'),
    url(r'^perros/(?P<pk>\d+)/borrar/$', perros_borrar.as_view(), name='borrar'),
    url(r'^perros/(?P<id>\d+)/editar/$', perros_actualizar, name='editar'),

    # RESTful API
    url(r'^rest-auth/', include('rest_auth.urls')),
    url(r'^perros/api/v1/$', perros_api_listar.as_view()),
    url(r'^perros/api/crear/$', perros_api_crear.as_view()),
    url(r'^perros/api/v2/$', perros_api.as_view()),

    # moderacion
    url(r'^perros/moderar/$', perros_moderacion, name='moderacion'),
    url(r'^perros/moderar/(?P<pk>\d+)/$', perros_moderacion_editar, name='editar-mod'),
    url(r'^perros/moderar/(?P<pk>\d+)/borrar$', perros_borrar_moderacion.as_view(), name='borrar'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# urlpatterns = format_suffix_patterns(urlpatterns)

templates/base.html
<!DOCTYPE html><html>
<head>
	 <meta charset="utf-8">
	<title>{% block title %} Cucha Noble {% endblock title %} </title>

{% load static %}
	 <link rel="stylesheet" type="text/css" href="{% static "perros/style.css" %}">

	<!-- MATERIALIZE CSS -->
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">

	<!-- MATERIALIZE JS-->
	<script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>
	<!--Import Google Icon Font-->
	<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

	<!--Let browser know website is optimized for mobile-->
	<meta name="viewport" content="width=device-width, initial-scale=1.0"/>


<!-- Header -> Navbar -->
	<header style="margin-bottom: 2em;">
		<nav class="orange darken-1">
			<div class="nav-wrapper container">
				<a href="{% url "perros:index" %}" class="brand-logo" >Cucha Noble</a>
				<ul id="nav-mobile" class="right hide-on-med-and-down">
					<li><a href="{% url "perros:lista" %}">Perros</a></li>
					<li><a href="{% url "perros:subir" %}">Subir Perro</a></li>
					{% if request.user.is_superuser %}
					<li><a href="{% url "perros:moderacion" %}">Moderar</a></li>
					{% endif %}
				</ul>
			</div>
		</nav>
	</header>



	<body class="body-cas">
		<!--Import jQuery before materialize.js-->

			<script>
			   $(document).ready(function() {
				  $('select').material_select();
			  });
			</script>
		<div class="container">
			{% block content %}
			{% endblock content %}
		</div>
	</body>


	<footer class="page-footer orange darken-2" style="margin-top: 3em;">
          <div class="container">
            <div class="row">
              <div class="col l6 s12">
                <h5 class="white-text">Cucha Noble</h5>
                <p class="grey-text text-lighten-4">Municipalidad de Río Gallegos</p>
              </div>
              <div class="col l4 offset-l2 s12">
                <h5 class="white-text">Links</h5>
                <ul>
                  <li><a class="grey-text text-lighten-3" href="#!">Link 1</a></li>
                  <li><a class="grey-text text-lighten-3" href="#!">Link 2</a></li>
                  <li><a class="grey-text text-lighten-3" href="#!">Link 3</a></li>
                  <li><a class="grey-text text-lighten-3" href="#!">Link 4</a></li>
                </ul>
              </div>
            </div>
          </div>
          <div class="footer-copyright">
            <div class="container">
            © 2017 Open-Source MIT License
            <a class="grey-text text-lighten-4 right" href="https://github.com/FacundoAlvarado9/cuchanoble">GitHub Project</a>
            </div>
          </div>
        </footer>
</html>

templates/base2.html
<!DOCTYPE html><html>
<head>
	 <meta charset="utf-8">
	<title>{% block title %} Cucha Noble {% endblock title %} </title>

{% load static %}
	 <link rel="stylesheet" type="text/css" href="{% static "perros/style.css" %}">

	<!-- MATERIALIZE CSS -->
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">

	<!-- MATERIALIZE JS-->
	<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/js/materialize.min.js"></script>
	<!--Import Google Icon Font-->
	<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

	<!--Let browser know website is optimized for mobile-->
	<meta name="viewport" content="width=device-width, initial-scale=1.0"/>


<!-- Header -> Navbar -->
	<header style="margin-bottom: 2em;">
		<nav class="orange darken-1">
			<div class="nav-wrapper container">
				<a href="{% url "perros:index" %}" class="brand-logo" >Cucha Noble</a>
				<ul id="nav-mobile" class="right hide-on-med-and-down">
					<li><a href="{% url "perros:lista" %}">Perros</a></li>
					<li><a href="{% url "perros:subir" %}">Subir Perro</a></li>
					{% if request.user.is_superuser %}
					<li><a href="{% url "perros:moderacion" %}">Moderar</a></li>
					{% endif %}


				</ul>
			</div>
		</nav>
	</header>



	<body class="body-cas">
		<!--Import jQuery before materialize.js-->
			<script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
			<script type="text/javascript" src="js/materialize.min.js"></script>
			<script>
			   $(document).ready(function() {
				  $('select').material_select();
			  });
			</script>
		<div>
			{% block content %}
			{% endblock content %}
		</div>
	</body>


	<footer class="page-footer orange darken-2" style="margin-top: 3em;">
          <div class="container">
            <div class="row">
              <div class="col l6 s12">
                <h5 class="white-text">Cucha Noble</h5>
                <p class="grey-text text-lighten-4">Municipalidad de Río Gallegos</p>
              </div>
              <div class="col l4 offset-l2 s12">
                <h5 class="white-text">Links</h5>
                <ul>
                  <li><a class="grey-text text-lighten-3" href="#!">Link 1</a></li>
                  <li><a class="grey-text text-lighten-3" href="#!">Link 2</a></li>
                  <li><a class="grey-text text-lighten-3" href="#!">Link 3</a></li>
                  <li><a class="grey-text text-lighten-3" href="#!">Link 4</a></li>
                </ul>
              </div>
            </div>
          </div>
          <div class="footer-copyright">
            <div class="container">
            © 2017 Open-Source MIT License
            <a class="grey-text text-lighten-4 right" href="https://github.com/FacundoAlvarado9/cuchanoble">GitHub Project</a>
            </div>
          </div>
        </footer>
</html>

templates/detalles.html
{% extends "base.html" %}

{% block content %}

{{perroDetalle.direccion}}<br>
{{perroDetalle.estado}}<br>
{{perroDetalle.tamano}}<br>
{{perroDetalle.subido_el}}<br>
{{perroDetalle.encontro_casa}}<br>
{{perroDetalle.contacto}}<br>
<img src="http://cuchanoble-static.s3.amazonaws.com/{{perroDetalle.imagen}}" alt="" width="100%"><br>
Subido por: {{subido}}<br>

	<a href="{% url "perros:editar" id=perroDetalle.id %}">Editar</a>
	{% if request.user.is_superuser %}
	<form method="POST" action="{% url "perros:borrar" pk=perroDetalle.pk %}">
   	{% csrf_token %}<input type="submit" value="DELETE">
	</form>
	{% endif %}

{{pe.author.id}}

{% endblock %}

templates/editar-moderacion.html
{% extends "base.html" %}

 {% load widget_tweaks %}
<title>{% block title %} Subir | {{block.super}} {% endblock title %}</title>

 {% block content %}

<div class="container">
    <h4 >Rellená el formulario</h4>
    <hr style="margin-bottom: 2em;">
</div>
<div class="container">
    <div class="card">
        <div class="card-content">
    	    <form method="POST" action="">{% csrf_token %}
            <!-- Form para completar al editar -->
              <!-- Checkear si encontro casa -->
              <h5>Para aprobar este perro<b>chequeá esta casilla</b> y da click en guardar</h5>
                {{form.aprobado}}
                {{form.aprobado.label_tag}}
              <h5>Si el perro encontró casa, <b>por favor chequeá esta casilla</b> y da click en guardar</h5>
                {% render_field form.encontro_casa placeholder="¿Encontro casa?" style="margin-bottom: 2em;" %}
                {{form.encontro_casa.label_tag}}
            <hr>
                {% render_field form.direccion placeholder="Barrio" style="margin-bottom: 2em;" %}
                {{form.edad.label_tag}}
                {% render_field form.edad class+="browser-default" style="margin-bottom: 2em;" %}
                {{form.sexo.label_tag}}
                {% render_field form.sexo class+="browser-default" style="margin-bottom: 2em;" %}
                {{form.tamano.label_tag}}
                {% render_field form.tamano class+="browser-default" style="margin-bottom: 2em;" %}
                {{form.estado.label_tag}}
                {% render_field form.estado class+="browser-default" style="margin-bottom: 2em;" %}
                {% render_field form.contacto placeholder="Número de contacto" style="margin-bottom: 2em;" %}
                <hr>
    	    <input class="btn" type="submit" value="Guardar">
          <br>
          <br>
          <hr>
    	</form>
      <h4>Eliminar perro</h4>
      <p>Cuidado, esta acción no tiene vuelta atrás</p>
      <form method="POST" action="{% url "perros:borrar" pk=perroDetalle.pk %}">
        {% csrf_token %}<input class="btn" type="submit" value="DELETE">
      </form>
        </div>
    </div>
</div>


{% endblock content %}

templates/editar.html
{% extends "base.html" %}

 {% load widget_tweaks %}
<title>{% block title %} Subir | {{block.super}} {% endblock title %}</title>

 {% block content %}

<div class="container">
    <h4 >Rellená el formulario</h4>
    <hr style="margin-bottom: 2em;">
</div>
<div class="container">
    <div class="card">
        <div class="card-content">
    	    <form method="POST" action="">{% csrf_token %}
            <!-- Form para completar al editar -->
              <!-- Checkear si encontro casa -->
              <h5>Si el perro encontró casa, por favor, <b>chequeá esta casilla</b> y da click en guardar</h5>
                {% render_field form.encontro_casa placeholder="¿Encontro casa?" style="margin-bottom: 2em;" %}
                {{form.encontro_casa.label_tag}}
            <hr>
                {% render_field form.direccion placeholder="Barrio" style="margin-bottom: 2em;" %}
                {{form.edad.label_tag}}
                {% render_field form.edad class+="browser-default" style="margin-bottom: 2em;" %}
                {{form.sexo.label_tag}}
                {% render_field form.sexo class+="browser-default" style="margin-bottom: 2em;" %}
                {{form.tamano.label_tag}}
                {% render_field form.tamano class+="browser-default" style="margin-bottom: 2em;" %}
                {{form.estado.label_tag}}
                {% render_field form.estado class+="browser-default" style="margin-bottom: 2em;" %}
                {% render_field form.contacto placeholder="Número de contacto" style="margin-bottom: 2em;" %}
                <p><b>Cambiar la imagen</b></p>
                <p><i>Presioná el boton "Subir Archivo" y sacá o seleccioná una foto</i></p>
                {% render_field form.imagen class+="btn" style="margin-bottom: 2em;" %}
                <hr>
    	    <input class="btn" type="submit" value="Guardar">
    	</form>
        </div>
    </div>
</div>


{% endblock content %}

templates/inicio.html
{% extends "base2.html" %}
<!--{% load static %}-->
{% block content %}


<!-- Template inicio -->


<div class="container" id="principal">
<div class="container">
    <div class="valign-wrapper mainsection">
        <div class="center-align">
        <h1 class="center-align">¡Bienvenido a Cucha Noble!</h1>
        <p class="center-align">El lugar donde los perros pueden encontrar una familia.</p>
        <a class="waves-effect waves-light btn" href="{% url "perros:lista" %}">Ver perros buscando familia</a>
        <a class="waves-effect waves-light btn" href="{% url "perros:subir" %}">Publicá un perro</a>
        </div>
    </div>
</div>
</div>

<div style="background-color: #f5f5f5; padding-bottom: 3em;">
<div class="row container">
    <div class="col s12 m4 l4">
        <div class="center" style="margin-top: 2em;">
            <i class="material-icons" style="font-size: 5rem; color: #ff7043;">pets</i>
            <h5 class="center" style="font-weight: bold;">¡Buscá un compañero!</h5>
            <p style="text-align: center;">Adoptá un perro que verdaderamente necesite una familia.</p>
        </div>
    </div>

    <div class="col s12 m4 l4">
        <div class="center" style="margin-top: 2em;">
            <i class="material-icons" style="font-size: 5rem; color: #ff7043;">arrow_upward</i>
            <h5 class="center" style="font-weight: bold;">Publicá un perro</h5>
            <p style="text-align: center;">Subí aquel perro de tu barrio que no tiene hogar.</p>
        </div>
    </div>

    <div class="col s12 m4 l4">
        <div class="center" style="margin-top: 2em;">
            <i class="material-icons" style="font-size: 5rem; color: #ff7043;">share</i>
            <h5 class="center" style="font-weight: bold;">Comparti</h5>
            <p style="text-align: center;">Compartí con tus conocidos, así todos adoptamos</p>
        </div>
    </div>


</div>
</div>


{% endblock content %}

templates/lista.html
{% extends "base.html" %}

<title>{% block title %}Lista de Perros | {{block.super}}{% endblock title %}</title>

{% block content %}

<div style="margin-top: 2em;">
	<h3>Lista de perros buscando hogar</h3>
	<hr style="margin-bottom: 1em;">
</div>

<!-- Para cada perro en el queryset, hacer un elemento de lista -->

<!-- Mensajes (exito) -->
{% if mensajes %}
	{% for mensaje in mensajes %}
		{% if mensaje.level == 26 %}
		<div class="col s12 m12 l6">
			<div class="card-panel green accent-3" style="padding: 0.5em;">
				<p style="color: #595959;">{{ mensaje }}</p>
			</div>
		</div>
		{% endif %}
	{% endfor %}
{% endif %}

{% for obj in queryset %}

<div class="row">
        <div class="col s12 m12 l6">
          <div class="card blue-grey darken-1">
						<div>
							<img src="http://cuchanoble-static.s3.amazonaws.com/{{obj.imagen}}" alt="" width="100%">
						</div>
            <div class="card-content white-text">
              <span class="card-title">Estoy en {{obj.direccion}}</span>
              <p>¡Hola! Estoy buscando una familia, soy {{obj.sexo}} y soy un {{obj.edad}}</p>
            </div>
            <div class="card-action">
              <a href="{% url "perros:detalles" id=obj.id %}">Más detalles</a>
              <!-- <a href="#">This is a link</a> -->
            </div>
          </div>
        </div>
      </div>

{% endfor %}

<!-- Subí un perro - Botón -->
<a href="{% url "perros:subir" %}" class="waves-effect waves-light btn"><i class="material-icons left">pets</i> ¡Subí un perro!</a>

<!-- {{user.first_name}} -->



{% endblock content %}

templates/moderacion.html
{% extends "base.html" %}

{% block content %}

{% for perro in queryset %}

<div class="row">
        <div class="col s12 m12 l6">
          <div class="card blue-grey darken-1">
						<div>
							<img src="http://cuchanoble-static.s3.amazonaws.com/{{perro.imagen}}" alt="" width="100%">
						</div>
            <div class="card-content white-text">
              <span class="card-title">Lugar: {{perro.direccion}}</span>
              <p>Sexo: {{perro.sexo}} | Edad: {{perro.edad}}</p>
              <p>Tamaño: {{perro.tamano}} | Estado: {{perro.estado}}</p>
              <p>Contacto: {{perro.contacto}}</p>
              <p>Autor: {{perro.author.first_name}} {{perro.author.last_name}}</p>
            </div>
            <div class="card-action">

              <button type="button" name="button"><a style="color: black;" href="{% url "perros:editar-mod" pk=perro.pk %}">Editar y aprobar</a></button>
                <br>
                <br>
              <form method="POST" action="{% url "perros:borrar" pk=perro.pk %}">
                {% csrf_token %}<input type="submit" value="Eliminar">
              </form>
            </div>
          </div>
        </div>
      </div>

{% endfor %}

{% endblock %}

templates/subir.html
{% extends "base.html" %}

 {% load widget_tweaks %}
<title>{% block title %} Subir | {{block.super}} {% endblock title %}</title>

 {% block content %}

<div class="container">
    <h4 >Rellená el formulario</h4>
    <hr style="margin-bottom: 2em;">
</div>
<div class="container">
    <div class="card">
        <div class="card-content">

    	    <form method="POST" action="" enctype="multipart/form-data">{% csrf_token %}
            <!-- Form para completar al editar -->
                {% render_field form.direccion placeholder="Barrio" style="margin-bottom: 2em;" %}
                {{form.edad.label_tag}}
                {% render_field form.edad class+="browser-default" style="margin-bottom: 2em;" %}
                {{form.sexo.label_tag}}
                {% render_field form.sexo class+="browser-default" style="margin-bottom: 2em;" %}
                {{form.tamano.label_tag}}
                {% render_field form.tamano class+="browser-default" style="margin-bottom: 2em;" %}
                {{form.estado.label_tag}}
                {% render_field form.estado class+="browser-default" style="margin-bottom: 2em;" %}
                {% render_field form.contacto placeholder="Número de contacto" style="margin-bottom: 2em;" %}
                <h5>Subi tu imagen</h5>
                <p>Presiona el boton "Subir Archivo" y sacá o seleccioná una foto</p>
                {% render_field form.imagen class+="btn" style="margin-bottom: 2em;" %}
                <hr>
    	    <input class="btn" type="submit" value="Subir Perro">
    	</form>

        </div>
    </div>
</div>


{% endblock content %}